name: Build Flutter App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Nur Ubuntu und Windows

    steps:
    # Code auschecken
    - name: Checkout code
      uses: actions/checkout@v3

    # Flutter einrichten
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'  # Setze die Flutter-Version auf 3.24.5

    # Installiere Abhängigkeiten für Linux
    - name: Install dependencies for Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
        sudo apt-get install -y build-essential  # C++ Compiler
        sudo apt-get install -y libgtk-3-dev   # GTK+3
        flutter doctor

    # Installiere Ninja für Windows
    - name: Install Ninja build tool (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install ninja
        flutter doctor

    # Flutter-Abhängigkeiten installieren
    - name: Install dependencies
      run: flutter pub get

    # Baue die App für das jeweilige OS
    - name: Build for ${{ matrix.os }}
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          flutter build linux --release
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then
          flutter build windows --release
        fi

    # Lade die Binaries hoch
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: flutter-app-${{ matrix.os }}
        path: |
          build/linux/release/bundle/**    # Für Linux
          build/windows/runner/Release/** # Für Windows
