name: Build Flutter App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest  # Linux-Job auf Ubuntu
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'  # Setze die Flutter-Version auf 3.24.5

    - name: Install dependencies for Linux
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
        sudo apt-get install -y build-essential  # C++ Compiler
        sudo apt-get install -y libgtk-3-dev   # GTK+3
        flutter doctor

    - name: Install dependencies
      run: flutter pub get

    - name: Build for Linux
      run: flutter build linux --release

    - name: List build directories
      run: |
        echo "Listing directories in the build folder:"
        ls -R build/

    - name: Upload binaries for Linux
      uses: actions/upload-artifact@v3
      with:
        name: flutter-app-linux
        path: build/linux/release/bundle/**  # Für Linux

  build-windows:
    name: Build for Windows
    runs-on: windows-latest  # Windows-Job auf Windows
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'  # Setze die Flutter-Version auf 3.24.5

    - name: Install Ninja build tool (Windows)
      shell: pwsh
      run: |
        choco install ninja
        flutter doctor

    - name: Install dependencies
      run: flutter pub get

    - name: Build for Windows
      run: flutter build windows --release

    - name: List build directories
      run: |
        echo "Listing directories in the build folder:"
        dir build

    - name: Upload binaries for Windows
      uses: actions/upload-artifact@v3
      with:
        name: flutter-app-windows
        path: build/windows/runner/Release/**  # Für Windows
